version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: incode-test-task-user
      POSTGRES_PASSWORD: incode-test-task-password
      POSTGRES_DB: incode-test-task-db